---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "mysql.fullname" .) }}
{{- $rootPwd := "" }}
{{- $userPwd := "" }}
{{- if $secret }}
{{- $rootPwd = index $secret.data "root_pwd" | b64dec }}
{{- $userPwd = index $secret.data "user_pwd" | b64dec }}
{{- end }}
stringData:
  user_pwd: {{ .Values.auth.userPwd | default $userPwd | default (randAlphaNum 18) | quote }}
  root_pwd: {{ .Values.auth.rootPwd | default $rootPwd | default (randAlphaNum 18) | quote }}
